# CI workflow for building, testing, and measuring coverage

name: Build, Test & Coverage DDF

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake cppcheck clang-tidy lcov

      - name: Run static analysis
        run: |
          cppcheck --enable=all --inconclusive --suppress=missingIncludeSystem --suppress=missingInclude src || true
          clang-tidy src/*.cpp -- -I./src || true

      - name: Configure & Build with coverage
        run: |
          mkdir build
          cd build
          cmake -DCODE_COVERAGE=ON ..
          cmake --build . --config Debug

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Capture coverage
        run: |
          cd build
          geninfo . --output-filename coverage.info --ignore-errors empty --memory 0
          lcov --remove coverage.info '/usr/*' --output-file coverage.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: build/coverage.info
          fail_ci_if_error: true
