name: Build & Test DDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup CMake
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Build with CMake
        run: |
          mkdir build && cd build
          cmake ..
          make

      - name: Run tests
        run: |
          cd build
          ctest --verbose

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build Docker image
        run: docker build -t ddf-ci .

      - name: Smoke Test Docker
        run: docker run --rm ddf-ci --help
