name: Build & Test DDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup CMake
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Build with CMake
        run: |
          mkdir build && cd build
          cmake ..
          make

      - name: Run tests
        run: |
          cd build
          ctest --verbose
