name: Build & Test DDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install static‑analysis tools
        run: sudo apt-get update && sudo apt-get install -y cppcheck clang-tidy

      - name: Static analysis (cppcheck & clang-tidy)
        run: |
          cppcheck --enable=all --inconclusive --error-exitcode=1 src
          clang-tidy src/*.cpp -- -I src

      - name: Setup CMake
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Build with CMake
        run: |
          mkdir build && cd build
          cmake ..
          make

      - name: Run tests
        run: |
          cd build
          ctest --verbose

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build Docker image
        run: docker build -t ddf-ci .

      - name: Smoke Test Docker
        run: docker run --rm ddf-ci --help
